In [1]:
import pandas as pd
import numpy as np
df = pd.read_parquet("yellow_tripdata_2025-01_new.parquet")

In [2]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,trip_duration
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,...,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0,8.350000
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,...,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0,2.550000
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,...,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0,1.950000
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,...,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0,5.566667
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,...,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0,3.533333

In [3]:
df.shape

(3475226, 21)

In [4]:
df.isnull().sum()

VendorID                      0
tpep_pickup_datetime          0
tpep_dropoff_datetime         0
passenger_count          540149
trip_distance                 0
RatecodeID               540149
store_and_fwd_flag       540149
PULocationID                  0
DOLocationID                  0
payment_type                  0
fare_amount                   0
extra                         0
mta_tax                       0
tip_amount                    0
tolls_amount                  0
improvement_surcharge         0
total_amount                  0
congestion_surcharge     540149
Airport_fee              540149
cbd_congestion_fee            0
trip_duration                 0
dtype: int64

In [5]:
df = pd.get_dummies(df,drop_first=True, dtype=int)

In [6]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,...,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,trip_duration,store_and_fwd_flag_Y
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,229,237,1,10.0,...,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0,8.350000,0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,236,237,1,5.1,...,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0,2.550000,0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,141,141,1,5.1,...,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0,1.950000,0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,244,244,2,7.2,...,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0,5.566667,0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,244,116,2,5.8,...,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0,3.533333,0

In [7]:
df.isnull().sum()

VendorID                      0
tpep_pickup_datetime          0
tpep_dropoff_datetime         0
passenger_count          540149
trip_distance                 0
RatecodeID               540149
PULocationID                  0
DOLocationID                  0
payment_type                  0
fare_amount                   0
extra                         0
mta_tax                       0
tip_amount                    0
tolls_amount                  0
improvement_surcharge         0
total_amount                  0
congestion_surcharge     540149
Airport_fee              540149
cbd_congestion_fee            0
trip_duration                 0
store_and_fwd_flag_Y          0
dtype: int64

# Removing null values
There are 4 columns cotains null value. 
1. Passenger count   : There is no trip without passenger. fill with 0 doesn't correct. We can fill with mean.
2. RatecodeID: This is an id. 0 and Mean is not the right approach. Mode can be considered as default RatecodeID.
3. congestion_surcharge: We can fill with 0. Some trip doesn't applicable for surcharge.
4. Airport_fee: We can fill with 0. All trip is not for Airport and doesn't applicable for surcharge.

In [8]:
import warnings
warnings.filterwarnings('ignore')

In [9]:
df["passenger_count"].fillna(df["passenger_count"].mean(), inplace=True)

In [10]:
df["RatecodeID"].fillna(df["RatecodeID"].mode()[0], inplace=True)

In [11]:
df["congestion_surcharge"].fillna(0, inplace=True)

In [12]:
df["Airport_fee"].fillna(0, inplace=True)

In [13]:
df.isnull().sum()

VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
PULocationID             0
DOLocationID             0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
congestion_surcharge     0
Airport_fee              0
cbd_congestion_fee       0
trip_duration            0
store_and_fwd_flag_Y     0
dtype: int64

All null values are removed.


# Removing Outliers

In [27]:
    ## Function is creating custom describe table with values named as descriptive
    def univariate(dataset,Quan):
        descriptive = pd.DataFrame(index=["Mean","Median","Mode","Q1:25 %","Q2:50 %","Q3:75 %","Q4:100 %","IQR","1.5Rule","Lesser","Greater", "Min", "Max"], columns=Quan)
        for col in Quan:
            descriptive[col]["Mean"]=dataset[col].mean()
            descriptive[col]["Median"]=dataset[col].median()
            descriptive[col]["Mode"]=dataset[col].mode()[0]
            descriptive[col]["Q1:25 %"] = dataset.describe()[col]["25%"]
            descriptive[col]["Q2:50 %"] = dataset.describe()[col]["50%"]    
            descriptive[col]["Q3:75 %"] = dataset.describe()[col]["75%"]    
            #descriptive[col]["99 %"] = np.percentile(dataset[col],99)
            descriptive[col]["Q4:100 %"] = dataset.describe()[col]["max"]
            descriptive[col]["IQR"] = dataset.describe()[col]["75%"] -  dataset.describe()[col]["25%"]
            descriptive[col]["1.5Rule"] =1.5*(dataset.describe()[col]["75%"] -  dataset.describe()[col]["25%"])
            descriptive[col]["Lesser"] =dataset.describe()[col]["25%"] - (1.5*(dataset.describe()[col]["75%"] -  dataset.describe()[col]["25%"]))
            descriptive[col]["Greater"] =dataset.describe()[col]["75%"] + (1.5*(dataset.describe()[col]["75%"] -  dataset.describe()[col]["25%"]))
            descriptive[col]["Min"] = dataset[col].min()
            descriptive[col]["Max"] = dataset[col].max()
            #descriptive[col]["Skew"] = dataset[col].skew()
            #descriptive[col]["Kurtosis"] = dataset[col].kurtosis()
            #descriptive[col]["Var"] = dataset[col].var()
            #descriptive[col]["Std"] = dataset[col].std()
        return descriptive

In [28]:
    ## Function is identifying any outlier contains in the columns and returning column names.
    def outlier_check(Quan,descriptive):
        lesser=[]
        greater=[]
        for cols in Quan:
            if descriptive[cols]["Min"]<descriptive[cols]["Lesser"]:
                lesser.append(cols)
            if descriptive[cols]["Max"]>descriptive[cols]["Greater"]:
                greater.append(cols)
        return lesser, greater

In [29]:
    ## Function is to replace lesser outlier value
    def replace_lesser_outlier(lesser,dataset,descriptive):
        for columnName in lesser:
            dataset[columnName][dataset[columnName]<descriptive[columnName]["Lesser"]] = descriptive[columnName]["Lesser"]
        return dataset

In [30]:
    ## Function is to replace greater outlier value
    def replace_greater_outlier(greater,dataset,descriptive):
        for columnName in greater:
            dataset[columnName][dataset[columnName]>descriptive[columnName]["Greater"]] = descriptive[columnName]["Greater"]
        return dataset

In [31]:
descriptive = univariate(df,df.columns)

In [32]:
descriptive

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,...,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,trip_duration,store_and_fwd_flag_Y
Mean,1.785428,2025-01-17 11:02:55.910964,2025-01-17 11:17:56.997901,1.297859,5.855126,2.252106,165.191576,164.125177,1.036623,17.081803,...,0.478099,2.959813,0.449308,0.954795,25.611292,1.879372,0.104652,0.483409,15.018116,0.0022
Median,2.0,2025-01-17 15:41:33,2025-01-17 15:59:34,1.0,1.67,1.0,162.0,162.0,1.0,12.11,...,0.5,2.45,0.0,1.0,19.95,2.5,0.0,0.75,11.7,0.0
Mode,2,2025-01-23 22:11:00,2025-01-19 00:00:00,1.0,0.0,1.0,161,236,1,8.6,...,0.5,0.0,0.0,1.0,17.7,2.5,0.0,0.75,9.0,0
Q1:25 %,2.0,2025-01-10 07:59:01,2025-01-10 08:15:29.500000,1.0,0.98,1.0,132.0,113.0,1.0,8.6,...,0.5,0.0,0.0,1.0,15.2,2.5,0.0,0.0,7.283333,0.0
Q2:50 %,2.0,2025-01-17 15:41:33,2025-01-17 15:59:34,1.0,1.67,1.0,162.0,162.0,1.0,12.11,...,0.5,2.45,0.0,1.0,19.95,2.5,0.0,0.75,11.7,0.0
Q3:75 %,2.0,2025-01-24 19:34:06,2025-01-24 19:48:31,1.297859,3.1,1.0,234.0,234.0,1.0,19.5,...,0.5,3.93,0.0,1.0,27.78,2.5,0.0,0.75,18.333333,0.0
Q4:100 %,7.0,2025-02-01 00:00:44,2025-02-01 23:44:11,9.0,276423.57,99.0,265.0,265.0,5.0,863372.12,...,10.5,400.0,170.94,1.0,863380.37,2.5,6.75,0.75,5626.316667,1.0
IQR,0.0,14 days 11:35:05,14 days 11:33:01.500000,0.297859,2.12,0.0,102.0,121.0,0.0,10.9,...,0.0,3.93,0.0,0.0,12.58,0.0,0.0,0.75,11.05,0.0
1.5Rule,0.0,21 days 17:22:37.500000,21 days 17:19:32.250000,0.446788,3.18,0.0,153.0,181.5,0.0,16.35,...,0.0,5.895,0.0,0.0,18.87,0.0,0.0,1.125,16.575,0.0
Lesser,2.0,2024-12-19 14:36:23.500000,2024-12-19 14:55:57.250000,0.553212,-2.2,1.0,-21.0,-68.5,1.0,-7.75,...,0.5,-5.895,0.0,1.0,-3.67,2.5,0.0,-1.125,-9.291667,0.0
Greater,2.0,2025-02-15 12:56:43.500000,2025-02-15 13:08:03.250000,1.744647,6.28,1.0,387.0,415.5,1.0,35.85,...,0.5,9.825,0.0,1.0,46.65,2.5,0.0,1.875,34.908333,0.0
Min,1,2024-12-31 20:47:55,2024-12-18 07:52:40,0.0,0.0,1.0,1,1,0,-900.0,...,-0.5,-86.0,-126.94,-1.0,-901.0,-2.5,-1.75,-0.75,-51472.316667,0
Max,7,2025-02-01 00:00:44,2025-02-01 23:44:11,9.0,276423.57,99.0,265,265,5,863372.12,...,10.5,400.0,170.94,1.0,863380.37,2.5,6.75,0.75,5626.316667,1

In [34]:
lesser,greater=outlier_check(df.columns,descriptive)

In [35]:
print("Lesser outlier in following columns:", lesser)
print("Greater outlier in following columns:",greater)

Lesser outlier in following columns: ['VendorID', 'tpep_dropoff_datetime', 'passenger_count', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'Airport_fee', 'trip_duration']
Greater outlier in following columns: ['VendorID', 'passenger_count', 'trip_distance', 'RatecodeID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'total_amount', 'Airport_fee', 'trip_duration', 'store_and_fwd_flag_Y']

In [42]:
df=replace_lesser_outlier(lesser,df,descriptive)

In [43]:
df=replace_greater_outlier(greater,df,descriptive)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3475226 entries, 0 to 3475225
Data columns (total 21 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   PULocationID           int32
 7   DOLocationID           int32
 8   payment_type           int64
 9   fare_amount            float64
 10  extra                  float64
 11  mta_tax                float64
 12  tip_amount             float64
 13  tolls_amount           float64
 14  improvement_surcharge  float64
 15  total_amount           float64
 16  congestion_surcharge   float64
 17  Airport_fee            float64
 18  cbd_congestion_fee     float64
 19  trip_duration          float64
 20  store_and_fwd_flag_Y   int64
dtypes: datetime64[us](2), float64(14), int32(3), int64(2)
memory usage: 517.0 MB

In [47]:
descriptive = univariate(df,df.columns)

In [48]:
lesser,greater=outlier_check(df.columns,descriptive)

In [49]:
print("Lesser outlier in following columns:", lesser)
print("Greater outlier in following columns:",greater)

Lesser outlier in following columns: []
Greater outlier in following columns: ['trip_distance', 'RatecodeID', 'store_and_fwd_flag_Y']

In [50]:
df=replace_greater_outlier(greater,df,descriptive)

In [51]:
df.to_parquet("yellow_tripdata_2025-01_clean.parquet")